#!/bin/bash

# Script para configurar los submodules
# Este script te ayudará a convertir los proyectos en submodules

echo "==================================================================="
echo "  Configuración de Submodules para Dominican Eaters LLM Project"
echo "==================================================================="
echo ""
echo "OPCIÓN RECOMENDADA: Crear repositorios GitHub separados y usar submodules"
echo ""
echo "Pasos a seguir:"
echo ""
echo "1. Crear 3 repositorios en GitHub:"
echo "   - https://github.com/lopezbec/books-eater"
echo "   - https://github.com/lopezbec/poems-eater"
echo "   - https://github.com/lopezbec/lyrics-eater"
echo ""
echo "2. Hacer push de cada proyecto a su repositorio:"
echo ""
echo "   # Books Eater"
echo "   cd books-eater"
echo "   git remote add origin git@github.com:lopezbec/books-eater.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo "   cd .."
echo ""
echo "   # Poems Eater"
echo "   cd poems-eater"
echo "   git remote add origin git@github.com:lopezbec/poems-eater.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo "   cd .."
echo ""
echo "   # Lyrics Eater"
echo "   cd lyrics-eater"
echo "   git remote add origin git@github.com:lopezbec/lyrics-eater.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo "   cd .."
echo ""
echo "3. Convertir a submodules:"
echo ""
echo "   # Hacer backup"
echo "   mv books-eater ../books-eater-backup"
echo "   mv poems-eater ../poems-eater-backup"
echo "   mv lyrics-eater ../lyrics-eater-backup"
echo ""
echo "   # Agregar como submodules"
echo "   git submodule add git@github.com:lopezbec/books-eater.git books-eater"
echo "   git submodule add git@github.com:lopezbec/poems-eater.git poems-eater"
echo "   git submodule add git@github.com:lopezbec/lyrics-eater.git lyrics-eater"
echo ""
echo "   # Commit y push"
echo "   git add .gitmodules books-eater poems-eater lyrics-eater"
echo "   git commit -m \"Configure projects as Git submodules\""
echo "   git push origin main"
echo ""
echo "4. Verificar:"
echo ""
echo "   git submodule status"
echo ""
echo "==================================================================="
echo ""
echo "ALTERNATIVA SIMPLE: Agregar todo al repositorio padre (sin submodules)"
echo ""
echo "   cd /home/manuujrodcruz/workspace/Dominican-eaters_Dominican_LLM_project"
echo "   git add books-eater poems-eater lyrics-eater"
echo "   git commit -m \"Add all scraper projects\""
echo "   git push origin main"
echo ""
echo "==================================================================="
echo ""
echo "Estado actual:"
echo "- ✓ Repositorio padre creado y configurado"
echo "- ✓ Remote de GitHub agregado"
echo "- ✓ README.md documentado"
echo "- ✓ SUBMODULES_SETUP.md con instrucciones detalladas"
echo "- ✓ Los 3 proyectos movidos al directorio padre"
echo "- ✓ Cada proyecto tiene su propio .git"
echo ""
echo "Siguiente paso: Elige una opción y ejecuta los comandos correspondientes"
echo ""
