"""Dataset of important Dominican poems."""

from typing import List, Tuple

# Format: (Título, Autor, Año, Género)
DOMINICAN_POEMS: List[Tuple[str, str, str, str]] = [
    # SALOMÉ UREÑA (1850-1897) - La Poetisa Nacional
    ("A la Patria", "Salomé Ureña", "1874", "Patriótico"),
    ("A la Educación", "Salomé Ureña", "1876", "Educativo"),
    ("La Gloria del Progreso", "Salomé Ureña", "N/A", "Filosófico"),
    ("Sueños y Realidades", "Salomé Ureña", "N/A", "Lírico"),
    ("Pensamientos en una Noche Triste", "Salomé Ureña", "N/A", "Melancólico"),
    ("La Vida", "Salomé Ureña", "N/A", "Filosófico"),
    ("A la Independencia", "Salomé Ureña", "N/A", "Patriótico"),
    ("El Triunfo de la Virtud", "Salomé Ureña", "N/A", "Moral"),
    
    # JOSÉ MARÍA HEREDIA (1803-1839) - Poeta Romántico
    ("Niágara", "José María Heredia", "1824", "Romántico"),
    ("En el Teocalli de Cholula", "José María Heredia", "1820", "Filosófico"),
    ("A la Estrella de Venus", "José María Heredia", "N/A", "Lírico"),
    ("El Juramento", "José María Heredia", "N/A", "Romántico"),
    ("En una Tempestad", "José María Heredia", "N/A", "Naturaleza"),
    ("Placidez", "José María Heredia", "N/A", "Contemplativo"),
    ("Al Océano", "José María Heredia", "N/A", "Naturaleza"),
    ("A Emilia", "José María Heredia", "N/A", "Amor"),
    
    # PEDRO MIR (1913-2000) - Poeta Nacional
    ("Hay un País en el Mundo", "Pedro Mir", "1949", "Épico"),
    ("Contracanto a Walt Whitman", "Pedro Mir", "1952", "Político"),
    ("La Mujer Viuda", "Pedro Mir", "N/A", "Social"),
    ("Amén de Mariposas", "Pedro Mir", "1969", "Histórico"),
    ("Cuando Amaban las Tierras Comunales", "Pedro Mir", "N/A", "Social"),
    ("Epigrama a la Burguesía", "Pedro Mir", "N/A", "Satírico"),
    ("Apocalipsis Íntimo", "Pedro Mir", "N/A", "Filosófico"),
    ("Celebración de la Alquimia", "Pedro Mir", "N/A", "Místico"),
    ("Poema de la Patria Nueva", "Pedro Mir", "N/A", "Patriótico"),
    
    # MANUEL DEL CABRAL (1907-1999) - Poeta Vanguardista
    ("Viaje Iluminado", "Manuel del Cabral", "1938", "Vanguardista"),
    ("Las Iniciales del Pulpo", "Manuel del Cabral", "N/A", "Experimental"),
    ("Poemas de la Sed", "Manuel del Cabral", "N/A", "Existencial"),
    ("Mensaje al Hombre Moderno", "Manuel del Cabral", "N/A", "Filosófico"),
    ("La Noche Oscura", "Manuel del Cabral", "N/A", "Místico"),
    ("Canto a la Esperanza", "Manuel del Cabral", "N/A", "Esperanzador"),
    ("El Regreso", "Manuel del Cabral", "N/A", "Nostálgico"),
    ("Tierra y Libertad", "Manuel del Cabral", "N/A", "Social"),
    
    # FRANKLIN MIESES BURGOS (1907-1999) - Poeta Cósmico
    ("Poesía Cósmica", "Franklin Mieses Burgos", "N/A", "Cósmico"),
    ("Los Ídolos de Fuego", "Franklin Mieses Burgos", "N/A", "Místico"),
    ("Himno al Cosmos", "Franklin Mieses Burgos", "N/A", "Cósmico"),
    ("La Voz del Silencio", "Franklin Mieses Burgos", "N/A", "Contemplativo"),
    ("Meditación Eterna", "Franklin Mieses Burgos", "N/A", "Filosófico"),
    ("Al Infinito", "Franklin Mieses Burgos", "N/A", "Trascendental"),
    
    # AIDA CARTAGENA PORTALATÍN (1918-1994) - Poetisa Moderna
    ("Variaciones para Domingo", "Aida Cartagena Portalatín", "1968", "Moderno"),
    ("Los Conjurados", "Aida Cartagena Portalatín", "N/A", "Político"),
    ("Canción para Dormir Soñando", "Aida Cartagena Portalatín", "N/A", "Lírico"),
    ("Vigilias", "Aida Cartagena Portalatín", "N/A", "Nocturno"),
    ("Nocturnos", "Aida Cartagena Portalatín", "N/A", "Nocturno"),
    ("Poema del Regreso", "Aida Cartagena Portalatín", "N/A", "Nostálgico"),
    
    # VIRTUDES ÁLVAREZ (1922-) - Poetisa Contemporánea
    ("Canciones Rusas", "Virtudes Álvarez", "1967", "Lírico"),
    ("Tú Culpable", "Virtudes Álvarez", "N/A", "Amor"),
    ("Voces en el Silencio", "Virtudes Álvarez", "N/A", "Introspectivo"),
    ("Memorias Nocturnas", "Virtudes Álvarez", "N/A", "Nocturno"),
    ("Pensamientos de Medianoche", "Virtudes Álvarez", "N/A", "Contemplativo"),
    
    # JOSÉ ACOSTA (1925-) - Poeta Moderno
    ("Territorios Extraños", "José Acosta", "1993", "Experimental"),
    ("Destrucciones", "José Acosta", "N/A", "Apocalíptico"),
    ("Jardín de Palabras", "José Acosta", "N/A", "Metapoético"),
    ("Viaje al Interior", "José Acosta", "N/A", "Introspectivo"),
    ("El Espejo Roto", "José Acosta", "N/A", "Existencial"),
    
    # SILVERIA BALBUENA (1952-) - Poetisa Contemporánea
    ("Imágenes de un Tiempo", "Silveria Balbuena", "N/A", "Temporal"),
    ("Voces en el Silencio", "Silveria Balbuena", "N/A", "Introspectivo"),
    ("Nocturnos Urbanos", "Silveria Balbuena", "N/A", "Urbano"),
    ("Reflexiones al Anochecer", "Silveria Balbuena", "N/A", "Contemplativo"),
    ("El Camino Olvidado", "Silveria Balbuena", "N/A", "Nostálgico"),
    
    # POETAS CLÁSICOS DOMINICANOS ADICIONALES
    ("Himno a la Independencia", "Nicolás Ureña de Mendoza", "N/A", "Patriótico"),
    ("La Sombra de Colón", "José Joaquín Pérez", "N/A", "Histórico"),
    ("Ecos del Pasado", "Mateo Morrison", "N/A", "Nostálgico"),
    ("Canción a la Esperanza", "Julio Andújar", "N/A", "Esperanzador"),
    ("Voces de la Isla", "Héctor Simón Díaz", "N/A", "Patriótico"),
    
    # POEMAS REVOLUCIONARIOS Y POLÍTICOS
    ("Canción Patriótica", "Anónimo Dominicano", "N/A", "Revolucionario"),
    ("Oda a la República", "Colectivo Popular", "N/A", "Político"),
    ("Versos de Independencia", "Tradicional", "N/A", "Patriótico"),
    ("La Lucha Continúa", "Poeta Moderno", "N/A", "Revolucionario"),
    ("Grito de Libertad", "Anónimo", "N/A", "Libertario"),
    
    # POEMAS DE AMOR Y ROMANCE
    ("Romance a la Amada", "Tradición Dominicana", "N/A", "Amor"),
    ("Nostalgia de Amor", "Tradición Dominicana", "N/A", "Romántico"),
    ("Corazón Perdido", "Tradición Dominicana", "N/A", "Amor"),
    ("Sueño de Amor", "Tradición Dominicana", "N/A", "Romántico"),
    ("Lamento del Enamorado", "Tradición Dominicana", "N/A", "Melancólico"),
    
    # POEMAS DE LA NATURALEZA DOMINICANA
    ("La Isla Verde", "Poeta Dominicano", "N/A", "Naturaleza"),
    ("Playas de Ensueño", "Poeta Dominicano", "N/A", "Naturaleza"),
    ("Montañas Sagradas", "Poeta Dominicano", "N/A", "Naturaleza"),
    ("Río de la Patria", "Poeta Dominicano", "N/A", "Naturaleza"),
    ("Tropical", "Poeta Dominicano", "N/A", "Naturaleza"),
    
    # POEMAS SATÍRICOS Y BURLONES
    ("Crítica Social", "Poeta Satírico", "N/A", "Satírico"),
    ("Burla de los Poderosos", "Poeta Satírico", "N/A", "Satírico"),
    ("Sátira Política", "Poeta Satírico", "N/A", "Satírico"),
    ("Mofa de la Hipocresía", "Poeta Satírico", "N/A", "Satírico"),
    ("Risa Amarga", "Poeta Satírico", "N/A", "Satírico"),
    
    # POEMAS TRADICIONALES Y ANÓNIMOS
    ("Décimas Dominicanas", "Compilación", "N/A", "Popular"),
    ("Coplas de Trovadores", "Tradicional", "N/A", "Popular"),
    ("Poesía Popular Dominicana", "Colectivo", "N/A", "Popular"),
    ("Versos de Pobre", "Anónimo", "N/A", "Popular"),
    ("Canción del Pueblero", "Tradicional", "N/A", "Popular"),
    
    # ALTAGRACIA SAVIÑON
    ("La Serenata De Schubert", "Altagracia Saviñon", "N/A", "Lírico"),
    ("Mi Vaso Verde", "Altagracia Saviñon", "N/A", "Lírico"),
    
    # ARTURO PELLERANO CASTRO
    ("A Ti Criolla", "Arturo Pellerano Castro", "N/A", "Romántico"),
    ("Americana", "Arturo Pellerano Castro", "N/A", "Patriótico"),
    ("Criolla", "Arturo Pellerano Castro", "N/A", "Costumbrista"),
    ("Las Hojas", "Arturo Pellerano Castro", "N/A", "Naturaleza"),
    
    # AÍDA CARTAGENA PORTALATÍN (ADICIONALES)
    ("Cantan A Las Mirabal", "Aída Cartagena Portalatín", "N/A", "Histórico"),
    ("Como Llorar La Muerte De Una Rosa", "Aída Cartagena Portalatín", "N/A", "Lírico"),
    ("Elegia", "Aída Cartagena Portalatín", "N/A", "Elegíaco"),
    ("Henri Matisse", "Aída Cartagena Portalatín", "N/A", "Arte"),
    ("Una Mujer Esta Sola", "Aída Cartagena Portalatín", "N/A", "Feminista"),
    ("Vispera Del Sueno", "Aída Cartagena Portalatín", "N/A", "Nocturno"),
    
    # BELKIS M. MARTE
    ("A Mi Madre", "Belkis M. Marte", "N/A", "Familiar"),
    ("A Mi Padre", "Belkis M. Marte", "N/A", "Familiar"),
    ("Anoranza", "Belkis M. Marte", "N/A", "Nostálgico"),
    ("Besar", "Belkis M. Marte", "N/A", "Amor"),
    ("El Verdadero Valor De Una Madre", "Belkis M. Marte", "N/A", "Familiar"),
    ("Espigas Secas", "Belkis M. Marte", "N/A", "Naturaleza"),
    ("Inventario", "Belkis M. Marte", "N/A", "Introspectivo"),
    ("Llevame Al Campo", "Belkis M. Marte", "N/A", "Naturaleza"),
    ("Oscura Primavera", "Belkis M. Marte", "N/A", "Naturaleza"),
    ("Otra Vez La Lluvia", "Belkis M. Marte", "N/A", "Naturaleza"),
    ("Pedazos", "Belkis M. Marte", "N/A", "Existencial"),
    ("Regreso A Casa", "Belkis M. Marte", "N/A", "Nostálgico"),
    ("Rehusate", "Belkis M. Marte", "N/A", "Amor"),
    ("Yo Soy Mi Tierra", "Belkis M. Marte", "N/A", "Patriótico"),
    ("Brindis Por La Madre", "Belkis M. Marte", "N/A", "Familiar"),
    ("Por El Labrador", "Belkis M. Marte", "N/A", "Social"),
    
    # CARMEN NATALIA
    ("Aqui Me Tienes Tu", "Carmen Natalia", "N/A", "Amor"),
    ("Darse", "Carmen Natalia", "N/A", "Filosófico"),
    ("Deja Que Descanse", "Carmen Natalia", "N/A", "Contemplativo"),
    ("El Estio", "Carmen Natalia", "N/A", "Naturaleza"),
    ("El Invierno", "Carmen Natalia", "N/A", "Naturaleza"),
    ("El Otono", "Carmen Natalia", "N/A", "Naturaleza"),
    ("Fantasia", "Carmen Natalia", "N/A", "Lírico"),
    ("He Vuelto A Esta A Solas Con Mi Alma", "Carmen Natalia", "N/A", "Introspectivo"),
    ("La Primavera", "Carmen Natalia", "N/A", "Naturaleza"),
    ("Mi Risa", "Carmen Natalia", "N/A", "Lírico"),
    ("Mipais", "Carmen Natalia", "N/A", "Patriótico"),
    ("No Digas A Nadie", "Carmen Natalia", "N/A", "Intimista"),
    ("Oda Heroica A Las Mirabal", "Carmen Natalia", "N/A", "Histórico"),
    ("Poema De La Madre Tierra", "Carmen Natalia", "N/A", "Naturaleza"),
    ("Una Tarde Sin Sol En Tu Cabana", "Carmen Natalia", "N/A", "Contemplativo"),
    
    # CÉSAR SÁNCHEZ BERAS
    ("Areito Para Todos", "César Sánchez Beras", "N/A", "Cultural"),
    ("Autorretrato", "César Sánchez Beras", "N/A", "Introspectivo"),
    ("Cuarenta Y Nueve", "César Sánchez Beras", "N/A", "Existencial"),
    ("Diaspora", "César Sánchez Beras", "N/A", "Social"),
    ("Dieciseis", "César Sánchez Beras", "N/A", "Lírico"),
    ("F De Flamboyan", "César Sánchez Beras", "N/A", "Naturaleza"),
    ("Las Alas De Su Sombrero", "César Sánchez Beras", "N/A", "Narrativo"),
    ("Loma Miranda", "César Sánchez Beras", "N/A", "Ecológico"),
    ("Poema Al Rio Ozama", "César Sánchez Beras", "N/A", "Naturaleza"),
    ("Ritual Song For Us All", "César Sánchez Beras", "N/A", "Cultural"),
    ("Seleccion De Haikus", "César Sánchez Beras", "N/A", "Haiku"),
    ("Seleccion Senryu", "César Sánchez Beras", "N/A", "Senryu"),
    ("Tres Relatos", "César Sánchez Beras", "N/A", "Narrativo"),
    ("Uno", "César Sánchez Beras", "N/A", "Minimalista"),
    ("Valentin Giro", "César Sánchez Beras", "N/A", "Homenaje"),
    
    # DOMINGO MORENO JIMENES
    ("Confidencias", "Domingo Moreno Jimenes", "N/A", "Intimista"),
    ("Desasimiento", "Domingo Moreno Jimenes", "N/A", "Filosófico"),
    ("El Diario De La Aldea", "Domingo Moreno Jimenes", "N/A", "Costumbrista"),
    ("La Nina Pola", "Domingo Moreno Jimenes", "N/A", "Narrativo"),
    ("La Siesta", "Domingo Moreno Jimenes", "N/A", "Contemplativo"),
    ("Melancolia", "Domingo Moreno Jimenes", "N/A", "Melancólico"),
    ("Poema De La Hija Reintegrada", "Domingo Moreno Jimenes", "N/A", "Familiar"),
    ("Rio Pueblo", "Domingo Moreno Jimenes", "N/A", "Social"),
    
    # EMILY DICKINSON (TRADUCCIONES)
    ("Emily Dickinson", "Emily Dickinson", "N/A", "Metapoético"),
    ("Mateo Morrison", "Emily Dickinson", "N/A", "Homenaje"),
    ("Naturaleza", "Emily Dickinson", "N/A", "Naturaleza"),
    ("Poema 1275", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 1461", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 1601", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 1715", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 1719", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 1751", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 288", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 47", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 49", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 536", "Emily Dickinson", "N/A", "Lírico"),
    ("Poema 540", "Emily Dickinson", "N/A", "Lírico"),
    
    # ENRIQUE HENRÍQUEZ
    ("Miserere", "Enrique Henríquez", "N/A", "Religioso"),
    ("Never More", "Enrique Henríquez", "N/A", "Melancólico"),
    
    # F. BERMÚDEZ Y ORTEGA
    ("Atrio", "F. Bermúdez y Ortega", "N/A", "Religioso"),
    ("A_Los_Heroes_Sin_Nombre", "F. Bermúdez y Ortega", "N/A", "Patriótico"),
    ("Campanas_De_La_Tarde", "F. Bermúdez y Ortega", "N/A", "Contemplativo"),
    ("Del_Arado", "F. Bermúdez y Ortega", "N/A", "Social"),
    ("Del_Estercolero", "F. Bermúdez y Ortega", "N/A", "Social"),
    ("Del_Lavadero", "F. Bermúdez y Ortega", "N/A", "Social"),
    ("Del_Yunque", "F. Bermúdez y Ortega", "N/A", "Social"),
    ("Desolacion", "F. Bermúdez y Ortega", "N/A", "Melancólico"),
    ("El_Mendigo", "F. Bermúdez y Ortega", "N/A", "Social"),
    ("El_Violin_Del_Mendigo", "F. Bermúdez y Ortega", "N/A", "Social"),
    ("En_Secreto", "F. Bermúdez y Ortega", "N/A", "Intimista"),
    ("Fantasia_Hebrea", "F. Bermúdez y Ortega", "N/A", "Cultural"),
    ("Hilos_De_Plata", "F. Bermúdez y Ortega", "N/A", "Lírico"),
    ("Ii", "F. Bermúdez y Ortega", "N/A", "Lírico"),
    ("Letanias_De_Amor", "F. Bermúdez y Ortega", "N/A", "Amor"),
    ("Leve_Y_Breve", "F. Bermúdez y Ortega", "N/A", "Minimalista"),
    ("Melodia_Breve", "F. Bermúdez y Ortega", "N/A", "Lírico"),
    ("Mensaje_Lirico", "F. Bermúdez y Ortega", "N/A", "Lírico"),
    ("Miseria", "F. Bermúdez y Ortega", "N/A", "Social"),
    ("Oh_Tardes_Adorables", "F. Bermúdez y Ortega", "N/A", "Contemplativo"),
    ("Paisaje", "F. Bermúdez y Ortega", "N/A", "Naturaleza"),
    ("Pincelada", "F. Bermúdez y Ortega", "N/A", "Impresionista"),
    ("Rimas_Para_Tus_Ojos", "F. Bermúdez y Ortega", "N/A", "Amor"),
    ("Romantica", "F. Bermúdez y Ortega", "N/A", "Romántico"),
    ("Serenamente_Gris", "F. Bermúdez y Ortega", "N/A", "Contemplativo"),
    ("Se_Murio_El_Avaro", "F. Bermúdez y Ortega", "N/A", "Narrativo"),
    ("Simbolo", "F. Bermúdez y Ortega", "N/A", "Simbólico"),
    
    # FABIO FIALLO
    ("Astro Muerto", "Fabio Fiallo", "N/A", "Melancólico"),
    ("El Silencio De Unos Ojos", "Fabio Fiallo", "N/A", "Amor"),
    ("En El Atrio", "Fabio Fiallo", "N/A", "Religioso"),
    ("En Tierra De Quisqueya", "Fabio Fiallo", "N/A", "Patriótico"),
    ("Era Una Tarde", "Fabio Fiallo", "N/A", "Romántico"),
    ("For Ever", "Fabio Fiallo", "N/A", "Amor"),
    ("Golgota Rosa", "Fabio Fiallo", "N/A", "Religioso"),
    ("Plenilunio", "Fabio Fiallo", "N/A", "Nocturno"),
    ("Quien Fuera Tu Espejo", "Fabio Fiallo", "N/A", "Amor"),
    ("Sandalo", "Fabio Fiallo", "N/A", "Sensorial"),
    
    # FRANKLIN MIESES BURGOS (ADICIONALES)
    ("Amor", "Franklin Mieses Burgos", "N/A", "Amor"),
    ("A_La_Sangre", "Franklin Mieses Burgos", "N/A", "Existencial"),
    ("Barro Inaugural", "Franklin Mieses Burgos", "N/A", "Cósmico"),
    ("Cancion De La Nina Que Queria Ser Sirena", "Franklin Mieses Burgos", "N/A", "Narrativo"),
    ("Cancion Del Sembrador De Voces", "Franklin Mieses Burgos", "N/A", "Social"),
    ("Cancion_Del_Mundo_Estatico", "Franklin Mieses Burgos", "N/A", "Filosófico"),
    ("Cancion_Del_Recuerdo_Feliz", "Franklin Mieses Burgos", "N/A", "Nostálgico"),
    ("Cancion_Del_Sembrador_De_Voces", "Franklin Mieses Burgos", "N/A", "Social"),
    ("Cancion_De_La_Amada_Sin_Presencia", "Franklin Mieses Burgos", "N/A", "Amor"),
    ("Cancion_De_La_Ni_A_Que_Iba_Sola", "Franklin Mieses Burgos", "N/A", "Narrativo"),
    ("Cancion_De_La_Noche_Larga", "Franklin Mieses Burgos", "N/A", "Nocturno"),
    ("Cancion_De_La_Voz_Florecida", "Franklin Mieses Burgos", "N/A", "Lírico"),
    ("Cancion_De_Los_Ojos_Que_Se_Fueron", "Franklin Mieses Burgos", "N/A", "Melancólico"),
    ("Cuando La Rosa Muere", "Franklin Mieses Burgos", "N/A", "Elegíaco"),
    ("Demonio De Ceniza", "Franklin Mieses Burgos", "N/A", "Místico"),
    ("Desvelado_Cain", "Franklin Mieses Burgos", "N/A", "Bíblico"),
    ("El Rio", "Franklin Mieses Burgos", "N/A", "Naturaleza"),
    ("Elogio De La Palma", "Franklin Mieses Burgos", "N/A", "Naturaleza"),
    ("Elogio_A_La_Palma", "Franklin Mieses Burgos", "N/A", "Naturaleza"),
    ("El_Cielo_Destruido", "Franklin Mieses Burgos", "N/A", "Apocalíptico"),
    ("El_Mensaje", "Franklin Mieses Burgos", "N/A", "Filosófico"),
    ("Esta Cancion Estaba Tirada Por El Suelo", "Franklin Mieses Burgos", "N/A", "Metapoético"),
    ("Este_Tacto", "Franklin Mieses Burgos", "N/A", "Sensorial"),
    ("Estrella Matutina", "Franklin Mieses Burgos", "N/A", "Cósmico"),
    ("Estrella_Matutina", "Franklin Mieses Burgos", "N/A", "Cósmico"),
    ("Eva_Recien_Hallada", "Franklin Mieses Burgos", "N/A", "Mítico"),
    ("Fabula_Ine_Fable_De_La_Ni_A_Loca", "Franklin Mieses Burgos", "N/A", "Narrativo"),
    ("Humilde Mayo", "Franklin Mieses Burgos", "N/A", "Naturaleza"),
    ("Humilde_Mayo", "Franklin Mieses Burgos", "N/A", "Naturaleza"),
    ("Las Dos Rosas", "Franklin Mieses Burgos", "N/A", "Simbólico"),
    ("Mensaje_A_Las_Palomas", "Franklin Mieses Burgos", "N/A", "Naturaleza"),
    ("Naturaleza", "Franklin Mieses Burgos", "N/A", "Naturaleza"),
    ("Paisaje Con Un Merengue Al Fondo", "Franklin Mieses Burgos", "N/A", "Cultural"),
    ("Primera_Evasion", "Franklin Mieses Burgos", "N/A", "Introspectivo"),
    ("Rosa En Vigilia", "Franklin Mieses Burgos", "N/A", "Lírico"),
    ("Segunda_Evasion", "Franklin Mieses Burgos", "N/A", "Introspectivo"),
    ("Sirena", "Franklin Mieses Burgos", "N/A", "Mítico"),
    ("Soneto_A_La_Muerte", "Franklin Mieses Burgos", "N/A", "Existencial"),
    ("Suelo", "Franklin Mieses Burgos", "N/A", "Filosófico"),
    ("Teoria_De_La_Vision_Profunda", "Franklin Mieses Burgos", "N/A", "Filosófico"),
    ("Viento", "Franklin Mieses Burgos", "N/A", "Naturaleza"),
    ("Viva_Muerte", "Franklin Mieses Burgos", "N/A", "Paradójico"),
    
    # GABRIELA MISTRAL (TRADUCCIONES/INFLUENCIA)
    ("Apegado A Mi", "Gabriela Mistral", "N/A", "Maternal"),
    ("Arbol Muerto", "Gabriela Mistral", "N/A", "Naturaleza"),
    ("Desolacion", "Gabriela Mistral", "N/A", "Melancólico"),
    ("Dona Primavera", "Gabriela Mistral", "N/A", "Infantil"),
    ("Dulzura", "Gabriela Mistral", "N/A", "Maternal"),
    ("El Amor Que Calla", "Gabriela Mistral", "N/A", "Amor"),
    ("Hablando Al Padre", "Gabriela Mistral", "N/A", "Religioso"),
    ("Himno Al Arbol", "Gabriela Mistral", "N/A", "Naturaleza"),
    ("Intima", "Gabriela Mistral", "N/A", "Intimista"),
    ("La Casa", "Gabriela Mistral", "N/A", "Hogar"),
    ("La Noche", "Gabriela Mistral", "N/A", "Nocturno"),
    ("La Tierra", "Gabriela Mistral", "N/A", "Naturaleza"),
    ("Meciendo", "Gabriela Mistral", "N/A", "Maternal"),
    ("Palabras Serenas", "Gabriela Mistral", "N/A", "Contemplativo"),
    ("Palmas De Cuba", "Gabriela Mistral", "N/A", "Naturaleza"),
    ("Poemas A La Naturaleza", "Gabriela Mistral", "N/A", "Naturaleza"),
    ("Riqueza", "Gabriela Mistral", "N/A", "Filosófico"),
    ("Rocio", "Gabriela Mistral", "N/A", "Naturaleza"),
    ("Tres Arboles", "Gabriela Mistral", "N/A", "Naturaleza"),
    
    # GASTÓN FERNANDO DELIGNE
    ("Angustias", "Gastón Fernando Deligne", "N/A", "Melancólico"),
    ("Aniquilamiento", "Gastón Fernando Deligne", "N/A", "Existencial"),
    ("Arriba El Pabellon", "Gastón Fernando Deligne", "N/A", "Patriótico"),
    ("Cantiga", "Gastón Fernando Deligne", "N/A", "Popular"),
    ("De La Selva", "Gastón Fernando Deligne", "N/A", "Naturaleza"),
    ("De_La_Selva", "Gastón Fernando Deligne", "N/A", "Naturaleza"),
    ("En El Botado", "Gastón Fernando Deligne", "N/A", "Costumbrista"),
    ("Entremes Olimpico", "Gastón Fernando Deligne", "N/A", "Satírico"),
    ("En_El_Botado", "Gastón Fernando Deligne", "N/A", "Costumbrista"),
    ("Esbozo Tipico", "Gastón Fernando Deligne", "N/A", "Costumbrista"),
    ("Incendio", "Gastón Fernando Deligne", "N/A", "Dramático"),
    ("Josefa A Perdomo", "Gastón Fernando Deligne", "N/A", "Homenaje"),
    ("Josefa_A_Perdomo", "Gastón Fernando Deligne", "N/A", "Homenaje"),
    ("Las Sanjuaneras", "Gastón Fernando Deligne", "N/A", "Cultural"),
    ("Los Galaripsos", "Gastón Fernando Deligne", "N/A", "Costumbrista"),
    ("Los_Galaripsos", "Gastón Fernando Deligne", "N/A", "Costumbrista"),
    ("Maireni", "Gastón Fernando Deligne", "N/A", "Narrativo"),
    ("Ololoi", "Gastón Fernando Deligne", "N/A", "Experimental"),
    ("Romance", "Gastón Fernando Deligne", "N/A", "Romántico"),
    ("Subjetiva", "Gastón Fernando Deligne", "N/A", "Introspectivo"),
    ("Webmaster", "Gastón Fernando Deligne", "N/A", "Moderno"),
    
    # HÉCTOR J. DÍAZ
    ("Alcohol", "Héctor J. Díaz", "N/A", "Social"),
    ("Alma Adentro", "Héctor J. Díaz", "N/A", "Introspectivo"),
    ("Altivez", "Héctor J. Díaz", "N/A", "Lírico"),
    ("Angustia", "Héctor J. Díaz", "N/A", "Existencial"),
    ("Ansias", "Héctor J. Díaz", "N/A", "Amor"),
    ("Como La He Visto", "Héctor J. Díaz", "N/A", "Amor"),
    ("Como Yo Te Quiero", "Héctor J. Díaz", "N/A", "Amor"),
    ("Contraste", "Héctor J. Díaz", "N/A", "Filosófico"),
    ("Conviccion", "Héctor J. Díaz", "N/A", "Filosófico"),
    ("Cumbre Y Abismo", "Héctor J. Díaz", "N/A", "Existencial"),
    ("Hace Dano Querer Como Te Quiero", "Héctor J. Díaz", "N/A", "Amor"),
    ("Lo Que Quiero", "Héctor J. Díaz", "N/A", "Deseo"),
    ("Mi Deceso", "Héctor J. Díaz", "N/A", "Existencial"),
    ("Posesion", "Héctor J. Díaz", "N/A", "Amor"),
    ("Remordimiento", "Héctor J. Díaz", "N/A", "Introspectivo"),
    ("Siempre", "Héctor J. Díaz", "N/A", "Amor"),
    ("Soneto", "Héctor J. Díaz", "N/A", "Clásico"),
    ("Yo Te Amo Asi", "Héctor J. Díaz", "N/A", "Amor"),
    
    # JOSEFA A. PERDOMO
    ("A Dios", "Josefa A. Perdomo", "N/A", "Religioso"),
    ("A La Noche", "Josefa A. Perdomo", "N/A", "Nocturno"),
    ("A La Poesia", "Josefa A. Perdomo", "N/A", "Metapoético"),
    ("A Mi Hermano R Perdomo Recuerdos De Mi Padre", "Josefa A. Perdomo", "N/A", "Familiar"),
    ("Al Ma R", "Josefa A. Perdomo", "N/A", "Amor"),
    ("Delicias Del Campo", "Josefa A. Perdomo", "N/A", "Naturaleza"),
    ("Desencanto", "Josefa A. Perdomo", "N/A", "Melancólico"),
    ("El Huracan Del 6 De Septiembre De 1883", "Josefa A. Perdomo", "N/A", "Histórico"),
    ("Naturaleza", "Josefa A. Perdomo", "N/A", "Naturaleza"),
    ("Noche De Insomnio", "Josefa A. Perdomo", "N/A", "Nocturno"),
    
    # JOSÉ JOAQUÍN PEREZ (ADICIONALES)
    ("Areito De Las Virgenes De Marien", "José Joaquín Perez", "N/A", "Indígena"),
    ("Ecos Del Destierro", "José Joaquín Perez", "N/A", "Exilio"),
    ("El Junco Verde", "José Joaquín Perez", "N/A", "Naturaleza"),
    ("La Vuelta Al Hogar", "José Joaquín Perez", "N/A", "Nostálgico"),
    
    # JOSÉ MARTÍ (TRADUCCIONES/INFLUENCIA)
    ("Banquete De Tiranos", "José Martí", "N/A", "Político"),
    ("Como Un Ave Que Cruza El Aire Claro", "José Martí", "N/A", "Lírico"),
    ("I Yo Soy Un Hombre Sincero", "José Martí", "N/A", "Lírico"),
    ("Ix Quiero A La Sombra De Un Ala", "José Martí", "N/A", "Amor"),
    ("Los Dos Principes", "José Martí", "N/A", "Narrativo"),
    ("Los Zapaticos De Rosa", "José Martí", "N/A", "Infantil"),
    ("Vi Si Quieren Que De Este Mundo", "José Martí", "N/A", "Filosófico"),
    ("Xiv Yo No Puedo Olvidar", "José Martí", "N/A", "Nostálgico"),
    ("Xxx El Rayo Surca Sangriento", "José Martí", "N/A", "Dramático"),
    ("Xxxix Cultivo Una Rosa Blanca", "José Martí", "N/A", "Lírico"),
    
    # JOSÉ MÁRMOL
    ("Al Nombre De Alguna Mujer", "José Mármol", "N/A", "Amor"),
    ("Esquicio Del Vuelo", "José Mármol", "N/A", "Lírico"),
    ("Insulantes", "José Mármol", "N/A", "Social"),
    ("Lenguaje Del Mar", "José Mármol", "N/A", "Naturaleza"),
    ("Para Cuando Regreses", "José Mármol", "N/A", "Amor"),
    ("Poema 24 Al Ozama Acuarela", "José Mármol", "N/A", "Naturaleza"),
    ("Retrato De Mujer", "José Mármol", "N/A", "Retrato"),
    ("Te Siento Caminar", "José Mármol", "N/A", "Amor"),
    ("Yo La Isla Dividida", "José Mármol", "N/A", "Político"),
    
    # JOSÉ NÚÑEZ DE CÁCERES
    ("A Los Vencedores De Palo Hincado", "José Núñez de Cáceres", "N/A", "Histórico"),
    ("El Abejarron Y La Abeja", "José Núñez de Cáceres", "N/A", "Fábula"),
    ("El Conejo Los Corderos Y El Pastor", "José Núñez de Cáceres", "N/A", "Fábula"),
    ("El Lobo Y La Rapos A", "José Núñez de Cáceres", "N/A", "Fábula"),
    ("El Mulo Y La Acemila", "José Núñez de Cáceres", "N/A", "Fábula"),
    ("El Palomo La Paloma Y La Lechuza", "José Núñez de Cáceres", "N/A", "Fábula"),
    ("La Arana Y El Aguila", "José Núñez de Cáceres", "N/A", "Fábula"),
    ("La Lechuza Y La Cig Ena", "José Núñez de Cáceres", "N/A", "Fábula"),
    ("Mi Pais", "José Núñez de Cáceres", "N/A", "Patriótico"),
    
    # JUAN ANTONIO ALIX
    ("Al_Publico", "Juan Antonio Alix", "N/A", "Popular"),
    ("Amor Y Geografia", "Juan Antonio Alix", "N/A", "Satírico"),
    ("Continuacion_De_Las_Decimas", "Juan Antonio Alix", "N/A", "Popular"),
    ("Dedicatoria", "Juan Antonio Alix", "N/A", "Dedicatoria"),
    ("De_La_Republica_Santiago", "Juan Antonio Alix", "N/A", "Histórico"),
    ("El Cometa Halley", "Juan Antonio Alix", "N/A", "Narrativo"),
    ("El Follon De Yamasa", "Juan Antonio Alix", "N/A", "Costumbrista"),
    ("El_Chivo_Moton", "Juan Antonio Alix", "N/A", "Popular"),
    ("El_Pleito_De_Pontezuela", "Juan Antonio Alix", "N/A", "Narrativo"),
    ("La Buena Vida Del Gato", "Juan Antonio Alix", "N/A", "Fábula"),
    ("Lamentaciones", "Juan Antonio Alix", "N/A", "Melancólico"),
    ("Las_Juntas_De_Fomento", "Juan Antonio Alix", "N/A", "Social"),
    ("La_Oreja_De_Nico_El_Loco", "Juan Antonio Alix", "N/A", "Costumbrista"),
    ("Los Mangos Bajitos", "Juan Antonio Alix", "N/A", "Popular"),
    ("Los_Mangos_Bajitos", "Juan Antonio Alix", "N/A", "Popular"),
    ("Los_Ninitos", "Juan Antonio Alix", "N/A", "Infantil"),
    ("Sin_Sudar", "Juan Antonio Alix", "N/A", "Social"),
    ("Un Campesino Dominicano", "Juan Antonio Alix", "N/A", "Costumbrista"),
    ("Un_Hijo_Desobediente", "Juan Antonio Alix", "N/A", "Moral"),
    ("Viva_La_Paz", "Juan Antonio Alix", "N/A", "Patriótico"),
    ("Y Se Fue El Cometa Halley Se Fue", "Juan Antonio Alix", "N/A", "Narrativo"),
    
    # JULIA DE BURGOS
    ("A Jose Marti", "Julia de Burgos", "N/A", "Homenaje"),
    ("A Julia De Burgos", "Julia de Burgos", "N/A", "Introspectivo"),
    ("Ay Ay Ay De La Grifa Negra", "Julia de Burgos", "N/A", "Identidad"),
    ("Cancion Amarga", "Julia de Burgos", "N/A", "Melancólico"),
    ("Cancion Hacia Adentro", "Julia de Burgos", "N/A", "Introspectivo"),
    ("Es Nuestra La Hora", "Julia de Burgos", "N/A", "Social"),
    ("Nada", "Julia de Burgos", "N/A", "Existencial"),
    ("Oh Mar No Esperes Mas", "Julia de Burgos", "N/A", "Naturaleza"),
    ("Poema Para Mi Muerte", "Julia de Burgos", "N/A", "Existencial"),
    ("Rio Grande De Loiza", "Julia de Burgos", "N/A", "Naturaleza"),
    ("Yo Fui La Mas Callada", "Julia de Burgos", "N/A", "Feminista"),
    ("Yo Misma Fui Mi Ruta", "Julia de Burgos", "N/A", "Feminista"),
    
    # MANUEL DEL CABRAL (ADICIONALES)
    ("A Concho Primo", "Manuel del Cabral", "N/A", "Popular"),
    ("Aire", "Manuel del Cabral", "N/A", "Experimental"),
    ("Aire_Durando", "Manuel del Cabral", "N/A", "Experimental"),
    ("Aire_Negro", "Manuel del Cabral", "N/A", "Identidad"),
    ("America Rota", "Manuel del Cabral", "N/A", "Político"),
    ("A_Quien_Viene_A_Ver_Usted", "Manuel del Cabral", "N/A", "Coloquial"),
    ("Camina", "Manuel del Cabral", "N/A", "Social"),
    ("Carta_A_Mi_Padre", "Manuel del Cabral", "N/A", "Familiar"),
    ("Compadre Mon", "Manuel del Cabral", "N/A", "Popular"),
    ("Donde_La_Voz_Parece_Mas_Del_Arbol", "Manuel del Cabral", "N/A", "Naturaleza"),
    ("Ellos", "Manuel del Cabral", "N/A", "Social"),
    ("Este_Negro", "Manuel del Cabral", "N/A", "Identidad"),
    ("Guitarra_Panadera", "Manuel del Cabral", "N/A", "Cultural"),
    ("Habla Compadre Mon", "Manuel del Cabral", "N/A", "Popular"),
    ("Habla_Compadre_Mon", "Manuel del Cabral", "N/A", "Popular"),
    ("Hombre_Y_Perro", "Manuel del Cabral", "N/A", "Narrativo"),
    ("Islas De Azucar Amarga", "Manuel del Cabral", "N/A", "Social"),
    ("Letra", "Manuel del Cabral", "N/A", "Metapoético"),
    ("Mujer_Con_Anillo", "Manuel del Cabral", "N/A", "Retrato"),
    ("Negro_Manso", "Manuel del Cabral", "N/A", "Identidad"),
    ("Negro_Siempre", "Manuel del Cabral", "N/A", "Identidad"),
    ("Negro_Sin_Nada_En_Tu_Casa", "Manuel del Cabral", "N/A", "Social"),
    ("Negro_Sin_Risa", "Manuel del Cabral", "N/A", "Social"),
    ("Negro_Sin_Zapatos", "Manuel del Cabral", "N/A", "Social"),
    ("Ni_O_Muerto_En_Un_Patio", "Manuel del Cabral", "N/A", "Dramático"),
    ("No_Le_Tire", "Manuel del Cabral", "N/A", "Social"),
    ("Oda_Para_Otro_Idioma", "Manuel del Cabral", "N/A", "Experimental"),
    ("Palabra", "Manuel del Cabral", "N/A", "Metapoético"),
    ("Pancho", "Manuel del Cabral", "N/A", "Popular"),
    ("Pulula", "Manuel del Cabral", "N/A", "Experimental"),
    ("Tres Apuntes", "Manuel del Cabral", "N/A", "Lírico"),
    ("Tropico Picapedrero", "Manuel del Cabral", "N/A", "Cultural"),
    ("Tropico_Suelto", "Manuel del Cabral", "N/A", "Cultural"),
    ("Un Recado De Mon Para Bolivar", "Manuel del Cabral", "N/A", "Histórico"),
    
    # MARÍA INÉS IACOMETTI
    ("A Proposito De Noviembre", "María Inés Iacometti", "N/A", "Temporal"),
    ("Angela", "María Inés Iacometti", "N/A", "Homenaje"),
    ("Borrosa", "María Inés Iacometti", "N/A", "Lírico"),
    ("Cristal En Gotas", "María Inés Iacometti", "N/A", "Impresionista"),
    ("El Dia Para Celebrarlo Es Hoy", "María Inés Iacometti", "N/A", "Filosófico"),
    ("Ellos Y Mi Casa", "María Inés Iacometti", "N/A", "Familiar"),
    ("Hasta Volvernos A Ver", "María Inés Iacometti", "N/A", "Despedida"),
    ("Homenaje De Tiempo", "María Inés Iacometti", "N/A", "Temporal"),
    ("Lapachos Y Prejuicios", "María Inés Iacometti", "N/A", "Social"),
    ("Mi Amor Por Siempre", "María Inés Iacometti", "N/A", "Amor"),
    ("No Mas", "María Inés Iacometti", "N/A", "Protesta"),
    ("Pachamama Mujer", "María Inés Iacometti", "N/A", "Feminista"),
    ("Papa", "María Inés Iacometti", "N/A", "Familiar"),
    ("Rhina Cercana", "María Inés Iacometti", "N/A", "Homenaje"),
    ("Rhina Espaillat", "María Inés Iacometti", "N/A", "Homenaje"),
    ("Si Le Faltaran Agostos", "María Inés Iacometti", "N/A", "Temporal"),
    ("Tus Manos Y Las Mias", "María Inés Iacometti", "N/A", "Intimista"),
    ("Yo Viento", "María Inés Iacometti", "N/A", "Naturaleza"),
    
    # MATEO MORRISON (ADICIONALES)
    ("Alicia Alonso", "Mateo Morrison", "N/A", "Homenaje"),
    ("Cuando Naci", "Mateo Morrison", "N/A", "Autobiográfico"),
    ("Desde El Atomo Gris", "Mateo Morrison", "N/A", "Existencial"),
    ("Ecologia", "Mateo Morrison", "N/A", "Ecológico"),
    ("Emily Dickinson", "Mateo Morrison", "N/A", "Homenaje"),
    ("En Principio", "Mateo Morrison", "N/A", "Filosófico"),
    ("Espasmos En La Noche", "Mateo Morrison", "N/A", "Nocturno"),
    ("La Camara Me Observa", "Mateo Morrison", "N/A", "Moderno"),
    ("La Musica De Tu Cuerpo", "Mateo Morrison", "N/A", "Amor"),
    ("Madre La Esperanza", "Mateo Morrison", "N/A", "Maternal"),
    ("Poema Del Dolor No Merecido", "Mateo Morrison", "N/A", "Existencial"),
    
    # MIGUEL ANTONIO JIMÉNEZ
    ("Amante_Del_Amor", "Miguel Antonio Jiménez", "N/A", "Amor"),
    ("A_C_S", "Miguel Antonio Jiménez", "N/A", "Dedicatoria"),
    ("Cosas", "Miguel Antonio Jiménez", "N/A", "Cotidiano"),
    ("Crece_Un_Arbol_En_Mi_Voz", "Miguel Antonio Jiménez", "N/A", "Metafórico"),
    ("Desolacion", "Miguel Antonio Jiménez", "N/A", "Melancólico"),
    ("Duarte", "Miguel Antonio Jiménez", "N/A", "Patriótico"),
    ("El_Amor", "Miguel Antonio Jiménez", "N/A", "Amor"),
    ("El_Arte", "Miguel Antonio Jiménez", "N/A", "Metapoético"),
    ("Epitafio", "Miguel Antonio Jiménez", "N/A", "Fúnebre"),
    ("Este_Sueno", "Miguel Antonio Jiménez", "N/A", "Onírico"),
    ("Fabula_Rosa", "Miguel Antonio Jiménez", "N/A", "Fábula"),
    ("Leon_Felipe", "Miguel Antonio Jiménez", "N/A", "Homenaje"),
    ("Meciendose_En_El_Agua", "Miguel Antonio Jiménez", "N/A", "Naturaleza"),
    ("Muchacha_Campesina", "Miguel Antonio Jiménez", "N/A", "Costumbrista"),
    ("Noche", "Miguel Antonio Jiménez", "N/A", "Nocturno"),
    ("Nostalgia_De_Pap", "Miguel Antonio Jiménez", "N/A", "Familiar"),
    ("Oda_A_Juan_Sanchez_Lamouth", "Miguel Antonio Jiménez", "N/A", "Homenaje"),
    ("Ser_O_No_Ser", "Miguel Antonio Jiménez", "N/A", "Existencial"),
    ("Si_Estas_Manos", "Miguel Antonio Jiménez", "N/A", "Corporal"),
    ("Soneto_Con_Estrambote", "Miguel Antonio Jiménez", "N/A", "Clásico"),
    ("Tacto_Fresco", "Miguel Antonio Jiménez", "N/A", "Sensorial"),
    ("Tibia_El_Alma", "Miguel Antonio Jiménez", "N/A", "Intimista"),
    ("Un_Dia_Lluvioso", "Miguel Antonio Jiménez", "N/A", "Naturaleza"),
    ("Vencido", "Miguel Antonio Jiménez", "N/A", "Existencial"),
    ("Xiv", "Miguel Antonio Jiménez", "N/A", "Numerado"),
    
    # NICOLÁS UREÑA DE MENDOZA (ADICIONALES)
    ("Pastorela", "Nicolás Ureña de Mendoza", "N/A", "Pastoral"),
    ("Un Guajiro En Bayaguana", "Nicolás Ureña de Mendoza", "N/A", "Costumbrista"),
    ("Un Guajiro Predilecto", "Nicolás Ureña de Mendoza", "N/A", "Costumbrista"),
    
    # OFELIA BERRIDO
    ("Anacaona", "Ofelia Berrido", "N/A", "Histórico"),
    ("I", "Ofelia Berrido", "N/A", "Numerado"),
    ("Ii", "Ofelia Berrido", "N/A", "Numerado"),
    ("Iii", "Ofelia Berrido", "N/A", "Numerado"),
    ("Invisibles Mundos", "Ofelia Berrido", "N/A", "Místico"),
    ("Iv", "Ofelia Berrido", "N/A", "Numerado"),
    ("Muero", "Ofelia Berrido", "N/A", "Existencial"),
    ("Vienen A Pedir Mi Alma", "Ofelia Berrido", "N/A", "Místico"),
    
    # OSVALDO BAZIL
    ("Los Cisnes De Ruben Dario", "Osvaldo Bazil", "N/A", "Homenaje"),
    ("Pequeno Nocturno", "Osvaldo Bazil", "N/A", "Nocturno"),
    
    # OTILIO VIGIL DÍAZ
    ("Arabesco", "Otilio Vigil Díaz", "N/A", "Ornamental"),
    ("Profesion De Fe", "Otilio Vigil Díaz", "N/A", "Filosófico"),
    ("Rapsodia", "Otilio Vigil Díaz", "N/A", "Musical"),
    ("Timpano De La Montana", "Otilio Vigil Díaz", "N/A", "Naturaleza"),
    ("Vision Lunar", "Otilio Vigil Díaz", "N/A", "Nocturno"),
    
    # PEDRO MIR (ADICIONALES)
    ("Alegria_De_La_Manana_Blanca", "Pedro Mir", "N/A", "Lírico"),
    ("Amen De Mariposas", "Pedro Mir", "N/A", "Histórico"),
    ("Amen_De_Mariposas", "Pedro Mir", "N/A", "Histórico"),
    ("A_La_Embajadora_Norteamericana", "Pedro Mir", "N/A", "Político"),
    ("Contracanto A Walt Whitman", "Pedro Mir", "N/A", "Homenaje"),
    ("El Huracan Neruda", "Pedro Mir", "N/A", "Homenaje"),
    ("Elegia_Del_14_De_Junio", "Pedro Mir", "N/A", "Histórico"),
    ("El_Portaaviones_Intrepido", "Pedro Mir", "N/A", "Político"),
    ("Hay Un Pais En El Mundo", "Pedro Mir", "N/A", "Épico"),
    ("Mano_Izquierda", "Pedro Mir", "N/A", "Político"),
    ("Ni_Un_Paso_Atras", "Pedro Mir", "N/A", "Combativo"),
    ("Pour_Toi", "Pedro Mir", "N/A", "Amor"),
    ("Si Alguien Quiere Saber Cual Es Mi Patria", "Pedro Mir", "N/A", "Patriótico"),
    ("Un_Pais_En_El_Mundo", "Pedro Mir", "N/A", "Épico"),
    
    # RAMÓN EMILIO JIMENEZ
    ("Belleza", "Ramón Emilio Jimenez", "N/A", "Estético"),
    ("Boda De Ruisenores", "Ramón Emilio Jimenez", "N/A", "Naturaleza"),
    ("El Encuentro Del Perro", "Ramón Emilio Jimenez", "N/A", "Narrativo"),
    ("Feliz Eres Labriego", "Ramón Emilio Jimenez", "N/A", "Social"),
    ("Halito Indigena", "Ramón Emilio Jimenez", "N/A", "Indígena"),
    ("Himno A La Tierra", "Ramón Emilio Jimenez", "N/A", "Naturaleza"),
    ("Mis Dos Madres Muertas", "Ramón Emilio Jimenez", "N/A", "Elegíaco"),
    ("Nino Eterno", "Ramón Emilio Jimenez", "N/A", "Filosófico"),
    ("Porque Amo A La Tierra", "Ramón Emilio Jimenez", "N/A", "Naturaleza"),
    
    # RENÉ DEL RISCO BERMÚDEZ
    ("A Ti", "René del Risco Bermúdez", "N/A", "Amor"),
    ("Ahora Que Vuelvo Tom", "René del Risco Bermúdez", "N/A", "Nostálgico"),
    ("El Viento Frio", "René del Risco Bermúdez", "N/A", "Naturaleza"),
    ("Entonces Para Que", "René del Risco Bermúdez", "N/A", "Existencial"),
    ("La Casa", "René del Risco Bermúdez", "N/A", "Hogar"),
    ("La Costurera", "René del Risco Bermúdez", "N/A", "Social"),
    ("Oda De La Manana Infantil", "René del Risco Bermúdez", "N/A", "Infantil"),
    ("Oye Patria", "René del Risco Bermúdez", "N/A", "Patriótico"),
    ("Todo Sucedera", "René del Risco Bermúdez", "N/A", "Profético"),
    
    # RHINA P. ESPAILLAT
    ("Biblioteca Virtual Miguel Cervantez", "Rhina P. Espaillat", "N/A", "Metapoético"),
    ("Bilingual Biling E", "Rhina P. Espaillat", "N/A", "Identidad"),
    ("Bodega", "Rhina P. Espaillat", "N/A", "Urbano"),
    ("Emily Dickinson", "Rhina P. Espaillat", "N/A", "Homenaje"),
    ("I Dreamt You Young", "Rhina P. Espaillat", "N/A", "Amor"),
    ("Like Ripened Grain", "Rhina P. Espaillat", "N/A", "Temporal"),
    ("Naci En La Ciudad Primada", "Rhina P. Espaillat", "N/A", "Autobiográfico"),
    ("Naturaleza", "Rhina P. Espaillat", "N/A", "Naturaleza"),
    ("Para Mi Tataranieto El Astropionero", "Rhina P. Espaillat", "N/A", "Futurista"),
    ("Solsticio Soltice", "Rhina P. Espaillat", "N/A", "Bilingüe"),
    ("Soneto 1", "Rhina P. Espaillat", "N/A", "Clásico"),
    ("Soneto 2", "Rhina P. Espaillat", "N/A", "Clásico"),
    ("Soneto 3", "Rhina P. Espaillat", "N/A", "Clásico"),
    ("Soneto 4", "Rhina P. Espaillat", "N/A", "Clásico"),
    
    # SALOMÉ UREÑA (ADICIONALES)
    ("A La Patria", "Salomé Ureña", "N/A", "Patriótico"),
    ("A Mi Madre", "Salomé Ureña", "N/A", "Familiar"),
    ("Amor Y Anhelo", "Salomé Ureña", "N/A", "Amor"),
    ("Anacaona Primera Parte", "Salomé Ureña", "N/A", "Histórico"),
    ("Angustias", "Salomé Ureña", "N/A", "Melancólico"),
    ("Caridad", "Salomé Ureña", "N/A", "Moral"),
    ("El Ave Y El Nido", "Salomé Ureña", "N/A", "Naturaleza"),
    ("El Cantar De Mis Cantares", "Salomé Ureña", "N/A", "Lírico"),
    ("En El Nacimiento De Mi Primogenito", "Salomé Ureña", "N/A", "Maternal"),
    ("Impresiones", "Salomé Ureña", "N/A", "Lírico"),
    ("La Fe En El Porvenir", "Salomé Ureña", "N/A", "Esperanzador"),
    ("La Llegada Del Invierno", "Salomé Ureña", "N/A", "Naturaleza"),
    ("Las Horas De Angustia", "Salomé Ureña", "N/A", "Melancólico"),
    ("Luz", "Salomé Ureña", "N/A", "Simbólico"),
    ("Melancolia", "Salomé Ureña", "N/A", "Melancólico"),
    ("Mi Ofrenda A La Patria", "Salomé Ureña", "N/A", "Patriótico"),
    ("Mi Pedro", "Salomé Ureña", "N/A", "Familiar"),
    ("Padre Mio", "Salomé Ureña", "N/A", "Familiar"),
    ("Quejas", "Salomé Ureña", "N/A", "Melancólico"),
    ("Ruinas", "Salomé Ureña", "N/A", "Elegíaco"),
    ("Sombras", "Salomé Ureña", "N/A", "Melancólico"),
    ("Suenos", "Salomé Ureña", "N/A", "Onírico"),
    ("Tristezas", "Salomé Ureña", "N/A", "Melancólico"),
    ("Una Esperanza", "Salomé Ureña", "N/A", "Esperanzador"),
    
    # TOMÁS HERNÁNDEZ FRANCO
    ("Poema De Chewing Gum", "Tomás Hernández Franco", "N/A", "Experimental"),
    ("Poema Del Feto", "Tomás Hernández Franco", "N/A", "Existencial"),
    ("Salutacion A Pancho Alegria", "Tomás Hernández Franco", "N/A", "Homenaje"),
    ("Yelida", "Tomás Hernández Franco", "N/A", "Narrativo"),
    
    # TRINA DE MOYA
    ("A La Vega", "Trina De Moya", "N/A", "Patriótico"),
    ("A Mi Esposo Anoranza", "Trina De Moya", "N/A", "Amor"),
    ("Canto A Moca", "Trina De Moya", "N/A", "Patriótico"),
    ("El Dia De Las Madres Himno A Las Madres", "Trina De Moya", "N/A", "Maternal"),
    ("La Patria Y La Mujer Dominicana", "Trina De Moya", "N/A", "Feminista"),
    ("Maria", "Trina De Moya", "N/A", "Religioso"),
    ("Soneto", "Trina De Moya", "N/A", "Clásico"),
]


def get_poems_as_objects():
    """
    Convert the poem tuples to Poem objects.
    
    Returns:
        List of Poem objects
    """
    from ..models.poem import Poem
    
    poems = []
    for idx, (titulo, autor, año, genero) in enumerate(DOMINICAN_POEMS, 1):
        poems.append(Poem(
            numero=idx,
            titulo=titulo,
            autor=autor,
            año=año,
            genero=genero
        ))
    
    return poems
