import {spawn,type ChildProcessWithoutNullStreams} from "node:child_process"
import {BoxRenderable,CliRenderEvents,InputRenderable,InputRenderableEvents,ScrollBoxRenderable,TextRenderable,createCliRenderer,type CliRenderer,type KeyEvent,type RenderContext} from "@opentui/core"
import {buildArgs,changeWorkflow,commandPreview,hasOutput,initialState,isStt,workflows,type Bootstrap,type FormState,type Preset} from "./model.ts"
const C={bg:"#0c0e0f",panel:"#121516",raised:"#181c1d",line:"#303637",muted:"#899192",fg:"#e6e9e7",green:"#77c38b",amber:"#d6ad65",red:"#e07373"}
type Field={key:keyof FormState;box:BoxRenderable;value:TextRenderable|InputRenderable;kind:"input"|"choice"|"toggle";options?:string[]}
export class DominicanEatersTui{
 readonly renderer:CliRenderer;readonly bootstrap:Bootstrap
 readonly state=initialState();readonly fields:Field[]=[];readonly presets:Preset[]
 private workspace!:BoxRenderable;private controls!:BoxRenderable;private pinned!:BoxRenderable;private form!:ScrollBoxRenderable;private preview!:TextRenderable;private status!:TextRenderable;private runState!:TextRenderable;private output!:TextRenderable;private outputState!:TextRenderable
 private focus=0;private maximized=false;private child:ChildProcessWithoutNullStreams|null=null;private logs:string[]=[];private started=0;private timer?:NodeJS.Timeout
 constructor(renderer:CliRenderer,bootstrap:Bootstrap){this.renderer=renderer;this.bootstrap=bootstrap;this.presets=bootstrap.presets;this.build()}
 private text(ctx:RenderContext,content:string,fg=C.fg,options:object={}){return new TextRenderable(ctx,{content,fg,...options})}
 private build(){const r=this.renderer;r.root.flexDirection="column"
  const top=new BoxRenderable(r,{height:3,flexDirection:"row",paddingX:2,alignItems:"center",backgroundColor:C.panel});top.add(this.text(r,"DOMINICAN EATERS",C.fg,{width:22}));top.add(this.text(r,"WORKFLOW CONSOLE",C.muted,{flexGrow:1}));this.runState=this.text(r,"● READY",C.green,{width:13});top.add(this.runState);r.root.add(top)
  this.workspace=new BoxRenderable(r,{flexGrow:1,flexDirection:"row",padding:1,gap:1});r.root.add(this.workspace);this.controls=new BoxRenderable(r,{width:42,minWidth:34,flexDirection:"column",border:true,borderColor:C.line,backgroundColor:C.panel});this.controls.add(this.text(r," RUN CONFIGURATION",C.muted,{height:2}));this.pinned=new BoxRenderable(r,{flexDirection:"column",paddingX:1,border:["bottom"],borderColor:C.line});this.controls.add(this.pinned);this.form=new ScrollBoxRenderable(r,{flexGrow:1,flexDirection:"column",paddingX:1});this.controls.add(this.form)
  this.choice("workflow","Workflow",workflows.map(x=>x.name));this.input("source","Source");this.input("output","Output directory");this.input("dataRoot","Dataset/data root override");this.input("artifactsRoot","Artifacts root override");this.choice("preset","Model preset",this.presets.map(p=>p.label));this.choice("device","Device",["auto","cpu","cuda"]);this.choice("precision","Precision",["auto","fp16","fp32","bf16"]);this.input("workerPython","Worker Python");this.input("warmupRuns","Warmup runs");this.input("requestTimeout","Timeout (seconds)");this.choice("shortAudioPolicy","Short audio",["reject","allow"]);this.input("minimumAudioSeconds","Minimum seconds");this.toggle("force","Force reprocessing");this.toggle("verifyHashes","Verify hashes");this.toggle("timestamps","Request timestamps")
  const dock=new BoxRenderable(r,{minHeight:8,flexDirection:"column",padding:1,backgroundColor:C.raised,border:["top"],borderColor:C.line});dock.add(this.text(r,"COMMAND",C.muted));this.preview=this.text(r,"",C.fg,{height:3});dock.add(this.preview);this.status=this.text(r,"Ready",C.green);dock.add(this.status);dock.add(this.text(r,"[ Ctrl+R Run ]  [ Ctrl+C Stop ]",C.green));this.controls.add(dock)
  const consoleBox=new BoxRenderable(r,{flexGrow:1,flexDirection:"column",border:true,borderColor:C.line,backgroundColor:C.panel});consoleBox.add(this.text(r," CONSOLE       Esc fields · Ctrl+O maximize · Ctrl+L clear",C.muted,{height:2}));this.output=this.text(r,"Waiting for a run",C.fg,{flexGrow:1,padding:1,selectable:true});consoleBox.add(this.output);this.outputState=this.text(r,"OUTPUT  waiting for a run",C.muted,{height:2,paddingLeft:1,backgroundColor:C.raised});consoleBox.add(this.outputState);this.workspace.add(this.controls);this.workspace.add(consoleBox);r.root.add(this.text(r," Tab navigate  ←/→ choose  Space toggle  Ctrl+R run  Ctrl+Q quit",C.muted,{height:1}))
  r.keyInput.on("keypress",(k:KeyEvent)=>this.key(k));r.on(CliRenderEvents.RESIZE,()=>this.responsive());this.sync();this.focusField(0);this.responsive()}
 private base(key:keyof FormState,label:string,value:TextRenderable|InputRenderable,kind:Field["kind"],options?:string[]){const box=new BoxRenderable(this.renderer,{height:4,flexDirection:"column",marginBottom:1,border:["left"],borderColor:C.line,paddingLeft:1});box.add(this.text(this.renderer,label,C.muted));box.add(value);(key==="workflow"||key==="preset"?this.pinned:this.form).add(box);this.fields.push({key,box,value,kind,options})}
 private input(key:keyof FormState,label:string){const v=new InputRenderable(this.renderer,{value:String(this.state[key]),textColor:C.fg,focusedTextColor:C.green,placeholderColor:C.muted,backgroundColor:C.bg,focusedBackgroundColor:C.bg});v.on(InputRenderableEvents.INPUT,(x:string)=>{(this.state as any)[key]=x;this.refresh()});this.base(key,label,v,"input")}
 private choice(k:keyof FormState,l:string,o:string[]){this.base(k,l,this.text(this.renderer,""),"choice",o)}private toggle(k:keyof FormState,l:string){this.base(k,l,this.text(this.renderer,""),"toggle")}
 private preset(){return this.presets.find(p=>p.id===this.state.preset)??this.presets[0]!}
 private visible(f:Field){const w=this.state.workflow,k=String(f.key);if(k==="output")return hasOutput(w);if(k==="dataRoot")return w==="config-validate"||w==="stt-preflight";if(k==="artifactsRoot")return w==="config-validate";if(["preset","device","precision"].includes(k))return isStt(w);if(k==="workerPython")return isStt(w)&&this.preset().execution==="worker";if(["warmupRuns","requestTimeout","shortAudioPolicy","minimumAudioSeconds","timestamps"].includes(k))return w==="stt-benchmark";if(k==="force")return["books-run","lyrics-run","lyrics-download-audio","poems-run"].includes(w);if(k==="verifyHashes")return isStt(w);return true}
 private render(f:Field){let d="";if(f.kind==="toggle")d=(this.state[f.key]?"[✓] ":"[ ] ")+"Space to toggle";else if(f.key==="workflow")d=workflows.find(x=>x.value===this.state.workflow)?.name??"";else if(f.key==="preset"){const p=this.preset();d=`${p.label} · ${p.status.toUpperCase()}`}else d=String(this.state[f.key]);(f.value as TextRenderable).content=`‹ ${d} ›`}
 private sync(){this.pinned.height=isStt(this.state.workflow)?10:5;for(const f of this.fields){f.box.visible=this.visible(f);if(f.kind==="input")(f.value as InputRenderable).value=String(this.state[f.key]);else this.render(f)}this.refresh();if(!this.fields[this.focus]?.box.visible)this.focusField(this.next(1))}
 private refresh(){this.preview.content=commandPreview(this.state,this.presets)}
 private focusField(i:number){const old=this.fields[this.focus];if(old){old.box.borderColor=C.line;old.value.blur()}this.focus=i;const f=this.fields[i]!;f.box.borderColor=C.green;f.value.focus();if(f.key!=="workflow"&&f.key!=="preset")this.form.scrollTo(f.box)}
 private next(dir:number){let i=this.focus;do{i=(i+dir+this.fields.length)%this.fields.length}while(!this.fields[i]!.box.visible);return i}
 private choose(dir:number){const f=this.fields[this.focus]!;if(f.kind==="toggle"){(this.state as any)[f.key]=!this.state[f.key];this.render(f);this.refresh();return}if(f.kind!=="choice")return;let vals=f.options??[];if(f.key==="workflow")vals=workflows.map(x=>x.value);if(f.key==="preset")vals=this.presets.map(p=>p.id);const cur=String(this.state[f.key]),v=vals[(vals.indexOf(cur)+dir+vals.length)%vals.length]!;if(f.key==="workflow")changeWorkflow(this.state,v as any);else{(this.state as any)[f.key]=v;if(f.key==="preset"){const p=this.preset();this.state.workerPython=p.workerPython;this.state.precision=p.precision||"auto";this.state.device=p.devices.includes("cuda")?"cuda":p.devices[0]||"auto"}}this.sync()}
 private key(k:KeyEvent){if(k.ctrl&&k.name==="q"){void this.quit();return}if(k.ctrl&&k.name==="r"){void this.run();return}if(k.ctrl&&k.name==="l"){this.logs=[];this.output.content="";this.outputState.content="OUTPUT  log cleared";return}if(k.ctrl&&k.name==="o"){this.maximized=!this.maximized;this.controls.visible=!this.maximized;this.workspace.padding=this.maximized?0:1;return}if(k.ctrl&&k.name==="c"&&this.child){this.child.kill("SIGTERM");this.setStatus("Stopping…",C.amber);return}if(k.name==="tab"){this.focusField(this.next(k.shift?-1:1));return}const f=this.fields[this.focus]!;if(f.kind!=="input"&&["left","right","space","return"].includes(k.name))this.choose(k.name==="left"?-1:1)}
 private responsive(){const narrow=this.renderer.root.width<86;this.workspace.flexDirection=narrow?"column":"row";this.controls.width=narrow?"100%":42;this.controls.height=narrow?"70%":"100%"}
 private line(m:string){this.logs.push(`${new Date().toLocaleTimeString("en-GB",{hour12:false})}  ${m}`);if(this.logs.length>1000)this.logs.shift();this.output.content=this.logs.join("\n");this.metrics()}
 private metrics(){const s=this.started?Math.floor((Date.now()-this.started)/1000):0;this.outputState.content=`OUTPUT  ${this.logs.length} lines · ${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")} · ${this.child?"running":"finished"}`}
 private setStatus(t:string,c:string){this.status.content=t;this.status.fg=c}
 async run(){if(this.child)return;let args:string[];try{args=buildArgs(this.state,this.presets)}catch(e){this.setStatus((e as Error).message,C.red);return}this.started=Date.now();this.logs=[];this.runState.content="● RUNNING";this.runState.fg=C.amber;this.setStatus("Running…",C.amber);const child=spawn(this.bootstrap.python,["-m","dominican_eaters",...args],{env:{...process.env,PYTHONUNBUFFERED:"1"}});this.child=child;this.line(`RUN   Starting ${this.state.workflow}`);this.line(`CMD   ${commandPreview(this.state,this.presets)}`);const consume=(b:Buffer)=>b.toString().split(/\r?\n/).filter(Boolean).forEach(x=>this.line(x));child.stdout.on("data",consume);child.stderr.on("data",consume);this.timer=setInterval(()=>this.metrics(),1000);child.on("error",e=>this.line(`ERR   ${e.message}`));child.on("close",code=>{this.child=null;if(this.timer)clearInterval(this.timer);const ok=code===0;this.line(ok?"OK    Completed successfully":`ERR   Process exited with status ${code}`);this.setStatus(ok?"Completed successfully":`Exited with status ${code}`,ok?C.green:C.red);this.runState.content="● READY";this.runState.fg=C.green;this.metrics()})}
 async quit(){if(this.child){this.child.kill("SIGTERM");await new Promise(r=>setTimeout(r,100))}this.renderer.destroy()}
}
export async function main(){const bootstrap=JSON.parse(process.env.DOMINICAN_EATERS_TUI_DATA??"") as Bootstrap;const renderer=await createCliRenderer({exitOnCtrlC:false,targetFps:30,backgroundColor:C.bg});new DominicanEatersTui(renderer,bootstrap)}
if(import.meta.url===`file://${process.argv[1]}`)await main()
