#!/usr/bin/env python3
"""Rank TTS outputs by ASR-backtranscription quality using Whisper."""

from __future__ import annotations

import argparse
import csv
import json
import statistics
from difflib import SequenceMatcher
from pathlib import Path
from typing import Dict, List

import whisper


def normalize_text(text: str) -> str:
    import re

    lowered = text.lower()
    lowered = re.sub(r"[^a-z0-9áéíóúüñ\s]", " ", lowered)
    return re.sub(r"\s+", " ", lowered).strip()


def words(text: str) -> List[str]:
    normalized = normalize_text(text)
    if not normalized:
        return []
    return normalized.split()


def word_error_rate(reference: str, hypothesis: str) -> float:
    ref = words(reference)
    hyp = words(hypothesis)
    if not ref:
        return 1.0 if hyp else 0.0

    d = [[0] * (len(hyp) + 1) for _ in range(len(ref) + 1)]
    for i in range(len(ref) + 1):
        d[i][0] = i
    for j in range(len(hyp) + 1):
        d[0][j] = j

    for i, ref_word in enumerate(ref, start=1):
        for j, hyp_word in enumerate(hyp, start=1):
            cost = 0 if ref_word == hyp_word else 1
            d[i][j] = min(
                d[i - 1][j] + 1,
                d[i][j - 1] + 1,
                d[i - 1][j - 1] + cost,
            )
    return d[len(ref)][len(hyp)] / len(ref)


def char_similarity(reference: str, hypothesis: str) -> float:
    return SequenceMatcher(
        None, normalize_text(reference), normalize_text(hypothesis)
    ).ratio()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate TTS WAV outputs with Whisper backtranscription"
    )
    parser.add_argument(
        "--manifest",
        default="outputs/run_manifest.json",
        help="Manifest generated by run_all_tts.sh",
    )
    parser.add_argument(
        "--output-dir",
        default="results",
        help="Directory to save leaderboard outputs",
    )
    parser.add_argument(
        "--whisper-model",
        default="base",
        help="Whisper model used for backtranscription",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest_path = Path(args.manifest).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    expected_text = manifest["text"]
    outputs = manifest["outputs"]

    model = whisper.load_model(args.whisper_model)

    rows = []
    for model_name, wav_path in outputs.items():
        path = Path(wav_path)
        if not path.exists():
            continue
        result = model.transcribe(str(path), language="es", fp16=False, verbose=False)
        transcript = (result.get("text") or "").strip()
        wer = word_error_rate(expected_text, transcript)
        csim = char_similarity(expected_text, transcript)
        rows.append(
            {
                "model": model_name,
                "wav_path": str(path),
                "wer": round(wer, 4),
                "char_similarity": round(csim, 4),
                "backtranscript": transcript,
            }
        )

    rows.sort(key=lambda r: r["wer"])

    details_csv = output_dir / "tts_scores_by_file.csv"
    with details_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "model",
                "wav_path",
                "wer",
                "char_similarity",
                "backtranscript",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)

    leaderboard = []
    grouped: Dict[str, List[Dict[str, object]]] = {}
    for row in rows:
        grouped.setdefault(str(row["model"]), []).append(row)

    for model_name, model_rows in grouped.items():
        wers = [float(r["wer"]) for r in model_rows]
        csims = [float(r["char_similarity"]) for r in model_rows]
        leaderboard.append(
            {
                "model": model_name,
                "samples": len(model_rows),
                "wer_mean": round(statistics.fmean(wers), 4),
                "char_similarity_mean": round(statistics.fmean(csims), 4),
            }
        )

    leaderboard.sort(key=lambda r: r["wer_mean"])

    leaderboard_json = output_dir / "tts_leaderboard.json"
    leaderboard_json.write_text(
        json.dumps({"models": leaderboard}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    leaderboard_csv = output_dir / "tts_leaderboard.csv"
    with leaderboard_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["model", "samples", "wer_mean", "char_similarity_mean"],
        )
        writer.writeheader()
        writer.writerows(leaderboard)

    if leaderboard:
        print(f"Best TTS model by ASR-back WER: {leaderboard[0]['model']}")
    print(f"Wrote: {details_csv}")
    print(f"Wrote: {leaderboard_json}")
    print(f"Wrote: {leaderboard_csv}")


if __name__ == "__main__":
    main()
