#!/usr/bin/env python3
"""Evaluate poem-benchmark TTS outputs with Whisper backtranscription."""

from __future__ import annotations

import argparse
import csv
import json
import statistics
from difflib import SequenceMatcher
from pathlib import Path
from typing import Dict, List

import whisper


def normalize_text(text: str) -> str:
    import re

    lowered = text.lower()
    lowered = re.sub(r"[^a-z0-9áéíóúüñ\s]", " ", lowered)
    return re.sub(r"\s+", " ", lowered).strip()


def words(text: str) -> List[str]:
    n = normalize_text(text)
    return n.split() if n else []


def word_error_rate(reference: str, hypothesis: str) -> float:
    ref = words(reference)
    hyp = words(hypothesis)
    if not ref:
        return 1.0 if hyp else 0.0

    d = [[0] * (len(hyp) + 1) for _ in range(len(ref) + 1)]
    for i in range(len(ref) + 1):
        d[i][0] = i
    for j in range(len(hyp) + 1):
        d[0][j] = j

    for i, rw in enumerate(ref, start=1):
        for j, hw in enumerate(hyp, start=1):
            cost = 0 if rw == hw else 1
            d[i][j] = min(
                d[i - 1][j] + 1,
                d[i][j - 1] + 1,
                d[i - 1][j - 1] + cost,
            )
    return d[len(ref)][len(hyp)] / len(ref)


def char_similarity(reference: str, hypothesis: str) -> float:
    return SequenceMatcher(
        None, normalize_text(reference), normalize_text(hypothesis)
    ).ratio()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate run_manifest_poems.json with Whisper"
    )
    parser.add_argument(
        "--manifest",
        default="outputs/poems_benchmark/run_manifest_poems.json",
        help="Manifest generated by run_poems_tts_benchmark.py",
    )
    parser.add_argument(
        "--output-dir",
        default="results/poems_benchmark",
        help="Directory for evaluation outputs",
    )
    parser.add_argument(
        "--whisper-model",
        default="base",
        help="Whisper model size (default: base)",
    )
    parser.add_argument(
        "--language",
        default="es",
        help="Language hint for Whisper transcription",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest_path = Path(args.manifest).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    rows = payload.get("rows", [])
    if not rows:
        raise RuntimeError("No rows found in manifest")

    model = whisper.load_model(args.whisper_model)

    scored_rows = []
    for row in rows:
        if row.get("status") != "ok":
            continue
        wav_path = Path(str(row["wav_path"]))
        if not wav_path.exists():
            continue

        reference = str(row.get("text", "")).strip()
        result = model.transcribe(
            str(wav_path), language=args.language, fp16=False, verbose=False
        )
        hypothesis = (result.get("text") or "").strip()

        wer = word_error_rate(reference, hypothesis)
        csim = char_similarity(reference, hypothesis)

        scored_rows.append(
            {
                "prompt_id": row.get("prompt_id", ""),
                "source_file": row.get("source_file", ""),
                "model": row.get("model", ""),
                "wav_path": str(wav_path),
                "wer": round(wer, 4),
                "char_similarity": round(csim, 4),
                "reference_text": reference,
                "backtranscript": hypothesis,
            }
        )

    details_csv = output_dir / "poems_tts_scores_by_file.csv"
    with details_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "prompt_id",
                "source_file",
                "model",
                "wav_path",
                "wer",
                "char_similarity",
                "reference_text",
                "backtranscript",
            ],
        )
        writer.writeheader()
        writer.writerows(scored_rows)

    grouped: Dict[str, List[Dict[str, object]]] = {}
    for row in scored_rows:
        grouped.setdefault(str(row["model"]), []).append(row)

    leaderboard = []
    for model_name, model_rows in grouped.items():
        wers = [float(r["wer"]) for r in model_rows]
        csims = [float(r["char_similarity"]) for r in model_rows]
        leaderboard.append(
            {
                "model": model_name,
                "samples": len(model_rows),
                "wer_mean": round(statistics.fmean(wers), 4),
                "wer_median": round(statistics.median(wers), 4),
                "char_similarity_mean": round(statistics.fmean(csims), 4),
            }
        )

    leaderboard.sort(key=lambda r: (r["wer_median"], r["wer_mean"]))

    leaderboard_json = output_dir / "poems_tts_leaderboard.json"
    leaderboard_json.write_text(
        json.dumps({"models": leaderboard}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    leaderboard_csv = output_dir / "poems_tts_leaderboard.csv"
    with leaderboard_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "model",
                "samples",
                "wer_mean",
                "wer_median",
                "char_similarity_mean",
            ],
        )
        writer.writeheader()
        writer.writerows(leaderboard)

    if leaderboard:
        print(f"Best model by median WER: {leaderboard[0]['model']}")
    print(f"Wrote: {details_csv}")
    print(f"Wrote: {leaderboard_json}")
    print(f"Wrote: {leaderboard_csv}")


if __name__ == "__main__":
    main()
